<!-- GitHub star -->
<a class="github-button" href="https://github.com/red/red" data-icon="octicon-star" data-show-count="true" aria-label="Star red/red on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/red/red/fork" data-icon="octicon-repo-forked" data-show-count="true" aria-label="Fork red/red on GitHub">Fork</a><!-- Tweet button -->
<!-- Twitter follow button -->
<a href="https://twitter.com/red_lang" class="twitter-follow-button" data-show-count="true">Follow @red_lang</a>
<!-- Github Button -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Twitter share button -->
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
